# Generated by Django 2.0 on 2017-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CountryPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.CharField(max_length=32)),
                ('data_year', models.CharField(max_length=16, null=True)),
                ('country', models.ForeignKey(on_delete=True, to='crawler.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='MinimumAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=16)),
                ('date_scraped', models.DateField()),
                ('country', models.ForeignKey(on_delete=True, to='crawler.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Misfits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('minimum_amount', models.CharField(max_length=32, null=True)),
                ('minimum_amount_year', models.CharField(max_length=16, null=True)),
                ('percent', models.CharField(max_length=16, null=True)),
                ('percent_year', models.CharField(max_length=16, null=True)),
                ('population_estimate', models.CharField(max_length=32, null=True)),
                ('population_year', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PovertyPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(max_length=16)),
                ('data_year', models.CharField(max_length=16, null=True)),
                ('date_scraped', models.DateField()),
                ('country', models.ForeignKey(on_delete=True, to='crawler.Countries')),
            ],
        ),
    ]
